runtime: nodejs10
env: standard
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always
  - url: /(.*\.(gif|png|jpg|ico|txt|js))$
    static_files: src/static/\1
    upload: src/static/.*\.(gif|png|jpg|ico|txt|js)$
    secure: always
  - url: /.*
    script: auto
    secure: always
instance_class: F2
env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: '8080'
automatic_scaling:
  min_instances: 0
