version: 2

defaults: &defaults
  docker:
    - image: node:10.13.0
  working_directory: /repo

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Lint
          command: yarn run lint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: /repo
          paths:
            - ./node_modules

  prepare_gcp:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: /repo
    steps:
      - checkout
      - run:
          name: Decode credential
          command: echo $GCLOUD_SERVICE_KEY | base64 -d > ./secret.json
      - run:
          name: Activate service account
          command: |
            gcloud auth activate-service-account --key-file=./secret.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - persist_to_workspace:
          root: /repo
          paths:
            - ./secret.json

  deploy:
    docker:
      - image: andoshin11/gcloud-sdk-node:10.13.0
    working_directory: /repo
    steps:
      - checkout
      - run:
          name: Built and Deploy
          command: GOOGLE_APPLICATION_CREDENTIALS=./secret.json yarn run deploy

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
      - prepare_gcp:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
            - prepare_gcp
          filters:
            branches:
              only: master
